# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio
<<<<<<< HEAD
    container_name: al-folio-website
    command: bash -c "
      rm -f Gemfile.lock
      && bundler exec jekyll serve --watch --port=8080 --host=0.0.0.0 --livereload --verbose --trace"
    ports:
      - 8080:8080
    volumes:
      - .:/srv/jekyll
=======
    ports:
      - 8080:8080
    volumes:
      - .:/srv/jekyll
>>>>>>> 347ea053 (Initial commit)
